Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -81,6 +81,20 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
 
+    services:
+      mysql:
+        image: mysql:8
+        env:
+          MYSQL_DATABASE: pdv_test
+          MYSQL_ROOT_PASSWORD: s3rp3nt3
+        ports:
+          - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping --silent"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
+
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
@@ -91,11 +105,27 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
+    - name: Wait for MySQL to be ready
+      run: |
+        echo "Waiting for MySQL service to be ready..."
+        for i in {30..0}; do
+          if docker exec $(docker ps -q -f name=mysql) mysqladmin ping -h "127.0.0.1" --silent &> /dev/null; then
+            echo "MySQL is up and running!"
+            break
+          fi
+          echo 'MySQL is unavailable - sleeping'
+          sleep 2
+        done
+        if [ "$i" = 0 ]; then
+          echo "MySQL failed to start in time."
+          exit 1
+        fi
+
     - name: Test with Maven
       run: mvn test
       env:
         SPRING_APPLICATION_NAME: pdv
-        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pdv?allowPublicKeyRetrieval=true&useSSL=false
+        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/pdv_test?allowPublicKeyRetrieval=true&useSSL=false
         SPRING_DATASOURCE_USERNAME: root
         SPRING_DATASOURCE_PASSWORD: s3rp3nt3
         SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
